### ISSUE TITLE
StrQueue needed?

### ISSUE THREAD

**Issue by 0816seung** [nsaripalli/Software-Dev-Part1#10]
StrQueue is not used in the tests, and Queue on its own handles Strings just fine (since Strings are Objects). Can you get rid of it?

**Comment by dermers** [comment]
We are working on adding tests for it. It is needed as per
1. old issues, and unfortunately the first team to request changes gets priority
2. Piazza posts and class lecture today.

**Comment by dermers** [comment]
Fixed tests
