### ISSUE TITLE
Your API doesn't specifically allow for Strings.

### ISSUE THREAD

**Issue by Buntry** [nsaripalli/Software-Dev-Part1#3]
What do you think about a separate class that allows for static support of pushing and popping String* directly.

**Comment by Buntry** [comment]
We can have a discussion on whether you want to include another class in the interface or how we should go about solving this issue because I think it's one the class will have at large. I'd rather we solve it here and spread the word.

**Comment by dermers** [comment]
We chose to specify our Queue like languages did before they had generics. In this, they can take in any object, and it's up to the user to worry about the types coming out. It's not my favorite situation, but I think it's preferable to having a ton of pointless sub-classes and making it much harder to use the Queue on new types that may defined in the future.

Also String* can be directly pushed, since it's an object, though it would need casting after a pop

**Comment by Buntry** [comment]
I think it would be easier to create another StrQueue class that does *not* subclass Queue, rather, it could either just compose a Queue and use dynamic casting OR it could just repeat the logic of the Queue and be more performant.

In either scenario, I think with StrList our prof. intends to have multiple classes for multiple types

**Comment by dermers** [comment]
StrList was a warmup, and needed to by typed so Sorting can be done internal. I'm not sure it's relevant here. If you feel strongly about have a StringQueue we can have one. It will be a subclass of Queue so that all that's needed is calling the parent methods and casting on the return ones

**Comment by dermers** [comment]
Nevermind, @331 seems to have clarified the need to have """typed""" data-structures. We'll add that to the spec

**Comment by dermers** [comment]
Also, we were given a StringQueue by our spec team so trust me when I say it's much easier when like that if the Queue's are only expected to take in things that are Objects (like String)

**Comment by Buntry** [comment]
I understand the duplication concerns, I wish we could have generic types too. Make sure that when you create StrQueue that it does not subclass Queue. We should use composition over subclassing. Also, it doesn't make sense to have a push(Object* o) on a StringQueue.

**Comment by dermers** [comment]
Should be fixed now, let me know what you think

**Comment by Buntry** [comment]
Looks good. You may want to include tests for specifically StrQueue.
