### ISSUE TITLE
Changing string.h for reconciliation

### ISSUE THREAD

**Issue by carloa21** [nsaripalli/Software-Dev-Part1#6]
Hello,

Lots of teams are using this [Piazza](https://piazza.com/class/k51bluky59n2jr?cid=166) post so they can reconcile their string.h and object.h specs. Please consider changing the method signatures in string.h to match below.

String:
int compare_to()
String* concat(String* other) 

Best,
Carlo

**Comment by dermers** [comment]
Lots of teams are using the student made one on Piazza as well. Our spec teams our using that, so and it is the most up to date. There are several known issues with the original ones you link that have been discussed in depth on Piazza
