### ISSUE TITLE
Please delete #pragma once in your main.cpp

### ISSUE THREAD

**Issue by Buntry** [nsaripalli/Software-Dev-Part1#7]
Not a crucial thing, but it ought not be there.

**Comment by dermers** [comment]
Assuming you mean test-queue.cpp but it should be fixed now

**Comment by Buntry** [comment]
Yup. I did.

**Comment by Buntry** [comment]
In the future, please close issues once they've actually been fixed.

**Comment by Buntry** [comment]
I rescind my comment, pragma once is no longer in your test-queue.cpp
