### ISSUE TITLE
cmp does not need to be virtual

### ISSUE THREAD

**Issue by 0816seung** [nsaripalli/Software-Dev-Part1#8]
In string.h, cmp is currently virtual which should not be needed. Can this be changed?
It is not virtual on this student centralized repo for String and Object:
https://github.com/chasebish/cwc_object_string/blob/master/string.h

**Comment by dermers** [comment]
It can be, and based on potential solutions to Warmup 3, it should be. I'm not sure it's a good idea to not be backwards compatible as much as possible.

**Comment by dermers** [comment]
This also shouldn't effect tests, as it currently has no children in the spec
