### ISSUE TITLE
Vague wording on comments for pop/peek

### ISSUE THREAD

**Issue by 0816seung** [nsaripalli/Software-Dev-Part1#9]
In queue.h, pop and peek refer to the "object at the end of this queue."
This is unclear which end it refers to (head or tail) and should be clarified.

**Comment by dermers** [comment]
The queue itself operates as a FIFO. "Head" or "Tail" are not part of the spec at all. If you chose to use a linked list in your implementation, it is up to you to make sure you know how to use it in a queue.

That being said, we can clarify the documentation

**Comment by dermers** [comment]
Fixed
